# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{customer_plugin}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Davis"]
  s.date = %q{2009-10-14}
  s.description = %q{This is a plugin for Redmine that can be used to track basic customer information}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "COPYRIGHT.txt",
     "CREDITS.txt",
     "GPL.txt",
     "README.rdoc",
     "Rakefile",
     "TAGS",
     "VERSION",
     "app/controllers/customers_controller.rb",
     "app/models/customer.rb",
     "app/views/customers/_form.html.erb",
     "app/views/customers/edit.html.erb",
     "app/views/customers/list.html.erb",
     "app/views/customers/new.html.erb",
     "app/views/customers/select.html.erb",
     "app/views/customers/show.html.erb",
     "config/locales/ca.yml",
     "config/locales/de.yml",
     "config/locales/en.yml",
     "config/locales/es.yml",
     "config/locales/fr.yml",
     "config/locales/it.yml",
     "init.rb",
     "lang/ca.yml",
     "lang/de.yml",
     "lang/en.yml",
     "lang/es.yml",
     "lang/fr.yml",
     "lang/it.yml",
     "rails/init.rb"
  ]
  s.homepage = %q{https://projects.littlestreamsoftware.com/projects/TODO}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{customer_plugin}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{This is a plugin for Redmine that can be used to track basic customer information}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/models/customer_spec.rb",
     "spec/controllers/customers_controller_spec.rb",
     "spec/sanity_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
